// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: orbit/shared/addressable.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Orbit.Shared.Proto {

  /// <summary>Holder for reflection information generated from orbit/shared/addressable.proto</summary>
  public static partial class AddressableReflection {

    #region Descriptor
    /// <summary>File descriptor for orbit/shared/addressable.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AddressableReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5vcmJpdC9zaGFyZWQvYWRkcmVzc2FibGUucHJvdG8SDE9yYml0LlNoYXJl",
            "ZBofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90bxoXb3JiaXQvc2hh",
            "cmVkL25vZGUucHJvdG8iWQoZQWRkcmVzc2FibGVSZWZlcmVuY2VQcm90bxIM",
            "CgR0eXBlGAEgASgJEi4KA2tleRgCIAEoCzIhLk9yYml0LlNoYXJlZC5BZGRy",
            "ZXNzYWJsZUtleVByb3RvImoKE0FkZHJlc3NhYmxlS2V5UHJvdG8SEgoIaW50",
            "MzJLZXkYASABKAVIABISCghpbnQ2NEtleRgCIAEoA0gAEhMKCXN0cmluZ0tl",
            "eRgDIAEoCUgAEg8KBW5vS2V5GAQgASgISABCBQoDa2V5ItwBChVBZGRyZXNz",
            "YWJsZUxlYXNlUHJvdG8SKQoGbm9kZUlkGAEgASgLMhkuT3JiaXQuU2hhcmVk",
            "Lk5vZGVJZFByb3RvEjoKCXJlZmVyZW5jZRgCIAEoCzInLk9yYml0LlNoYXJl",
            "ZC5BZGRyZXNzYWJsZVJlZmVyZW5jZVByb3RvEiwKCHJlbmV3X2F0GAMgASgL",
            "MhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgpleHBpcmVzX2F0GAQg",
            "ASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJ/CiNOYW1lc3BhY2Vk",
            "QWRkcmVzc2FibGVSZWZlcmVuY2VQcm90bxIRCgluYW1lc3BhY2UYASABKAkS",
            "RQoUYWRkcmVzc2FibGVSZWZlcmVuY2UYAiABKAsyJy5PcmJpdC5TaGFyZWQu",
            "QWRkcmVzc2FibGVSZWZlcmVuY2VQcm90b0IVqgIST3JiaXQuU2hhcmVkLlBy",
            "b3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Orbit.Shared.Proto.NodeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.AddressableReferenceProto), global::Orbit.Shared.Proto.AddressableReferenceProto.Parser, new[]{ "Type", "Key" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.AddressableKeyProto), global::Orbit.Shared.Proto.AddressableKeyProto.Parser, new[]{ "Int32Key", "Int64Key", "StringKey", "NoKey" }, new[]{ "Key" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.AddressableLeaseProto), global::Orbit.Shared.Proto.AddressableLeaseProto.Parser, new[]{ "NodeId", "Reference", "RenewAt", "ExpiresAt" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.NamespacedAddressableReferenceProto), global::Orbit.Shared.Proto.NamespacedAddressableReferenceProto.Parser, new[]{ "Namespace", "AddressableReference" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AddressableReferenceProto : pb::IMessage<AddressableReferenceProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AddressableReferenceProto> _parser = new pb::MessageParser<AddressableReferenceProto>(() => new AddressableReferenceProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddressableReferenceProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.AddressableReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressableReferenceProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressableReferenceProto(AddressableReferenceProto other) : this() {
      type_ = other.type_;
      key_ = other.key_ != null ? other.key_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressableReferenceProto Clone() {
      return new AddressableReferenceProto(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 2;
    private global::Orbit.Shared.Proto.AddressableKeyProto key_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.AddressableKeyProto Key {
      get { return key_; }
      set {
        key_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddressableReferenceProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddressableReferenceProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Key, other.Key)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (key_ != null) hash ^= Key.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (key_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Key);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (key_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Key);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (key_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Key);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddressableReferenceProto other) {
      if (other == null) {
        return;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      if (other.key_ != null) {
        if (key_ == null) {
          Key = new global::Orbit.Shared.Proto.AddressableKeyProto();
        }
        Key.MergeFrom(other.Key);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            if (key_ == null) {
              Key = new global::Orbit.Shared.Proto.AddressableKeyProto();
            }
            input.ReadMessage(Key);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            if (key_ == null) {
              Key = new global::Orbit.Shared.Proto.AddressableKeyProto();
            }
            input.ReadMessage(Key);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AddressableKeyProto : pb::IMessage<AddressableKeyProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AddressableKeyProto> _parser = new pb::MessageParser<AddressableKeyProto>(() => new AddressableKeyProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddressableKeyProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.AddressableReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressableKeyProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressableKeyProto(AddressableKeyProto other) : this() {
      switch (other.KeyCase) {
        case KeyOneofCase.Int32Key:
          Int32Key = other.Int32Key;
          break;
        case KeyOneofCase.Int64Key:
          Int64Key = other.Int64Key;
          break;
        case KeyOneofCase.StringKey:
          StringKey = other.StringKey;
          break;
        case KeyOneofCase.NoKey:
          NoKey = other.NoKey;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressableKeyProto Clone() {
      return new AddressableKeyProto(this);
    }

    /// <summary>Field number for the "int32Key" field.</summary>
    public const int Int32KeyFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Int32Key {
      get { return keyCase_ == KeyOneofCase.Int32Key ? (int) key_ : 0; }
      set {
        key_ = value;
        keyCase_ = KeyOneofCase.Int32Key;
      }
    }

    /// <summary>Field number for the "int64Key" field.</summary>
    public const int Int64KeyFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Int64Key {
      get { return keyCase_ == KeyOneofCase.Int64Key ? (long) key_ : 0L; }
      set {
        key_ = value;
        keyCase_ = KeyOneofCase.Int64Key;
      }
    }

    /// <summary>Field number for the "stringKey" field.</summary>
    public const int StringKeyFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringKey {
      get { return keyCase_ == KeyOneofCase.StringKey ? (string) key_ : ""; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        keyCase_ = KeyOneofCase.StringKey;
      }
    }

    /// <summary>Field number for the "noKey" field.</summary>
    public const int NoKeyFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool NoKey {
      get { return keyCase_ == KeyOneofCase.NoKey ? (bool) key_ : false; }
      set {
        key_ = value;
        keyCase_ = KeyOneofCase.NoKey;
      }
    }

    private object key_;
    /// <summary>Enum of possible cases for the "key" oneof.</summary>
    public enum KeyOneofCase {
      None = 0,
      Int32Key = 1,
      Int64Key = 2,
      StringKey = 3,
      NoKey = 4,
    }
    private KeyOneofCase keyCase_ = KeyOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KeyOneofCase KeyCase {
      get { return keyCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearKey() {
      keyCase_ = KeyOneofCase.None;
      key_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddressableKeyProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddressableKeyProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Int32Key != other.Int32Key) return false;
      if (Int64Key != other.Int64Key) return false;
      if (StringKey != other.StringKey) return false;
      if (NoKey != other.NoKey) return false;
      if (KeyCase != other.KeyCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (keyCase_ == KeyOneofCase.Int32Key) hash ^= Int32Key.GetHashCode();
      if (keyCase_ == KeyOneofCase.Int64Key) hash ^= Int64Key.GetHashCode();
      if (keyCase_ == KeyOneofCase.StringKey) hash ^= StringKey.GetHashCode();
      if (keyCase_ == KeyOneofCase.NoKey) hash ^= NoKey.GetHashCode();
      hash ^= (int) keyCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (keyCase_ == KeyOneofCase.Int32Key) {
        output.WriteRawTag(8);
        output.WriteInt32(Int32Key);
      }
      if (keyCase_ == KeyOneofCase.Int64Key) {
        output.WriteRawTag(16);
        output.WriteInt64(Int64Key);
      }
      if (keyCase_ == KeyOneofCase.StringKey) {
        output.WriteRawTag(26);
        output.WriteString(StringKey);
      }
      if (keyCase_ == KeyOneofCase.NoKey) {
        output.WriteRawTag(32);
        output.WriteBool(NoKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (keyCase_ == KeyOneofCase.Int32Key) {
        output.WriteRawTag(8);
        output.WriteInt32(Int32Key);
      }
      if (keyCase_ == KeyOneofCase.Int64Key) {
        output.WriteRawTag(16);
        output.WriteInt64(Int64Key);
      }
      if (keyCase_ == KeyOneofCase.StringKey) {
        output.WriteRawTag(26);
        output.WriteString(StringKey);
      }
      if (keyCase_ == KeyOneofCase.NoKey) {
        output.WriteRawTag(32);
        output.WriteBool(NoKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (keyCase_ == KeyOneofCase.Int32Key) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int32Key);
      }
      if (keyCase_ == KeyOneofCase.Int64Key) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Int64Key);
      }
      if (keyCase_ == KeyOneofCase.StringKey) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringKey);
      }
      if (keyCase_ == KeyOneofCase.NoKey) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddressableKeyProto other) {
      if (other == null) {
        return;
      }
      switch (other.KeyCase) {
        case KeyOneofCase.Int32Key:
          Int32Key = other.Int32Key;
          break;
        case KeyOneofCase.Int64Key:
          Int64Key = other.Int64Key;
          break;
        case KeyOneofCase.StringKey:
          StringKey = other.StringKey;
          break;
        case KeyOneofCase.NoKey:
          NoKey = other.NoKey;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Int32Key = input.ReadInt32();
            break;
          }
          case 16: {
            Int64Key = input.ReadInt64();
            break;
          }
          case 26: {
            StringKey = input.ReadString();
            break;
          }
          case 32: {
            NoKey = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Int32Key = input.ReadInt32();
            break;
          }
          case 16: {
            Int64Key = input.ReadInt64();
            break;
          }
          case 26: {
            StringKey = input.ReadString();
            break;
          }
          case 32: {
            NoKey = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AddressableLeaseProto : pb::IMessage<AddressableLeaseProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AddressableLeaseProto> _parser = new pb::MessageParser<AddressableLeaseProto>(() => new AddressableLeaseProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddressableLeaseProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.AddressableReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressableLeaseProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressableLeaseProto(AddressableLeaseProto other) : this() {
      nodeId_ = other.nodeId_ != null ? other.nodeId_.Clone() : null;
      reference_ = other.reference_ != null ? other.reference_.Clone() : null;
      renewAt_ = other.renewAt_ != null ? other.renewAt_.Clone() : null;
      expiresAt_ = other.expiresAt_ != null ? other.expiresAt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressableLeaseProto Clone() {
      return new AddressableLeaseProto(this);
    }

    /// <summary>Field number for the "nodeId" field.</summary>
    public const int NodeIdFieldNumber = 1;
    private global::Orbit.Shared.Proto.NodeIdProto nodeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.NodeIdProto NodeId {
      get { return nodeId_; }
      set {
        nodeId_ = value;
      }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 2;
    private global::Orbit.Shared.Proto.AddressableReferenceProto reference_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.AddressableReferenceProto Reference {
      get { return reference_; }
      set {
        reference_ = value;
      }
    }

    /// <summary>Field number for the "renew_at" field.</summary>
    public const int RenewAtFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp renewAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp RenewAt {
      get { return renewAt_; }
      set {
        renewAt_ = value;
      }
    }

    /// <summary>Field number for the "expires_at" field.</summary>
    public const int ExpiresAtFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp expiresAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ExpiresAt {
      get { return expiresAt_; }
      set {
        expiresAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddressableLeaseProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddressableLeaseProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(NodeId, other.NodeId)) return false;
      if (!object.Equals(Reference, other.Reference)) return false;
      if (!object.Equals(RenewAt, other.RenewAt)) return false;
      if (!object.Equals(ExpiresAt, other.ExpiresAt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (nodeId_ != null) hash ^= NodeId.GetHashCode();
      if (reference_ != null) hash ^= Reference.GetHashCode();
      if (renewAt_ != null) hash ^= RenewAt.GetHashCode();
      if (expiresAt_ != null) hash ^= ExpiresAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (nodeId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(NodeId);
      }
      if (reference_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Reference);
      }
      if (renewAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RenewAt);
      }
      if (expiresAt_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ExpiresAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (nodeId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(NodeId);
      }
      if (reference_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Reference);
      }
      if (renewAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RenewAt);
      }
      if (expiresAt_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ExpiresAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (nodeId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NodeId);
      }
      if (reference_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reference);
      }
      if (renewAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RenewAt);
      }
      if (expiresAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExpiresAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddressableLeaseProto other) {
      if (other == null) {
        return;
      }
      if (other.nodeId_ != null) {
        if (nodeId_ == null) {
          NodeId = new global::Orbit.Shared.Proto.NodeIdProto();
        }
        NodeId.MergeFrom(other.NodeId);
      }
      if (other.reference_ != null) {
        if (reference_ == null) {
          Reference = new global::Orbit.Shared.Proto.AddressableReferenceProto();
        }
        Reference.MergeFrom(other.Reference);
      }
      if (other.renewAt_ != null) {
        if (renewAt_ == null) {
          RenewAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        RenewAt.MergeFrom(other.RenewAt);
      }
      if (other.expiresAt_ != null) {
        if (expiresAt_ == null) {
          ExpiresAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ExpiresAt.MergeFrom(other.ExpiresAt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (nodeId_ == null) {
              NodeId = new global::Orbit.Shared.Proto.NodeIdProto();
            }
            input.ReadMessage(NodeId);
            break;
          }
          case 18: {
            if (reference_ == null) {
              Reference = new global::Orbit.Shared.Proto.AddressableReferenceProto();
            }
            input.ReadMessage(Reference);
            break;
          }
          case 26: {
            if (renewAt_ == null) {
              RenewAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(RenewAt);
            break;
          }
          case 34: {
            if (expiresAt_ == null) {
              ExpiresAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ExpiresAt);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (nodeId_ == null) {
              NodeId = new global::Orbit.Shared.Proto.NodeIdProto();
            }
            input.ReadMessage(NodeId);
            break;
          }
          case 18: {
            if (reference_ == null) {
              Reference = new global::Orbit.Shared.Proto.AddressableReferenceProto();
            }
            input.ReadMessage(Reference);
            break;
          }
          case 26: {
            if (renewAt_ == null) {
              RenewAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(RenewAt);
            break;
          }
          case 34: {
            if (expiresAt_ == null) {
              ExpiresAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ExpiresAt);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NamespacedAddressableReferenceProto : pb::IMessage<NamespacedAddressableReferenceProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NamespacedAddressableReferenceProto> _parser = new pb::MessageParser<NamespacedAddressableReferenceProto>(() => new NamespacedAddressableReferenceProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NamespacedAddressableReferenceProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.AddressableReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NamespacedAddressableReferenceProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NamespacedAddressableReferenceProto(NamespacedAddressableReferenceProto other) : this() {
      namespace_ = other.namespace_;
      addressableReference_ = other.addressableReference_ != null ? other.addressableReference_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NamespacedAddressableReferenceProto Clone() {
      return new NamespacedAddressableReferenceProto(this);
    }

    /// <summary>Field number for the "namespace" field.</summary>
    public const int NamespaceFieldNumber = 1;
    private string namespace_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Namespace {
      get { return namespace_; }
      set {
        namespace_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "addressableReference" field.</summary>
    public const int AddressableReferenceFieldNumber = 2;
    private global::Orbit.Shared.Proto.AddressableReferenceProto addressableReference_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.AddressableReferenceProto AddressableReference {
      get { return addressableReference_; }
      set {
        addressableReference_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NamespacedAddressableReferenceProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NamespacedAddressableReferenceProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Namespace != other.Namespace) return false;
      if (!object.Equals(AddressableReference, other.AddressableReference)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Namespace.Length != 0) hash ^= Namespace.GetHashCode();
      if (addressableReference_ != null) hash ^= AddressableReference.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Namespace.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Namespace);
      }
      if (addressableReference_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AddressableReference);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Namespace.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Namespace);
      }
      if (addressableReference_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AddressableReference);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Namespace.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Namespace);
      }
      if (addressableReference_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AddressableReference);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NamespacedAddressableReferenceProto other) {
      if (other == null) {
        return;
      }
      if (other.Namespace.Length != 0) {
        Namespace = other.Namespace;
      }
      if (other.addressableReference_ != null) {
        if (addressableReference_ == null) {
          AddressableReference = new global::Orbit.Shared.Proto.AddressableReferenceProto();
        }
        AddressableReference.MergeFrom(other.AddressableReference);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Namespace = input.ReadString();
            break;
          }
          case 18: {
            if (addressableReference_ == null) {
              AddressableReference = new global::Orbit.Shared.Proto.AddressableReferenceProto();
            }
            input.ReadMessage(AddressableReference);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Namespace = input.ReadString();
            break;
          }
          case 18: {
            if (addressableReference_ == null) {
              AddressableReference = new global::Orbit.Shared.Proto.AddressableReferenceProto();
            }
            input.ReadMessage(AddressableReference);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
