// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: orbit/shared/addressable_management.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Orbit.Shared.Proto {
  public static partial class AddressableManagement
  {
    static readonly string __ServiceName = "Orbit.Shared.AddressableManagement";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Orbit.Shared.Proto.RenewAddressableLeaseRequestProto> __Marshaller_Orbit_Shared_RenewAddressableLeaseRequestProto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Orbit.Shared.Proto.RenewAddressableLeaseRequestProto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Orbit.Shared.Proto.RenewAddressableLeaseResponseProto> __Marshaller_Orbit_Shared_RenewAddressableLeaseResponseProto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Orbit.Shared.Proto.RenewAddressableLeaseResponseProto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Orbit.Shared.Proto.AbandonAddressableLeaseRequestProto> __Marshaller_Orbit_Shared_AbandonAddressableLeaseRequestProto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Orbit.Shared.Proto.AbandonAddressableLeaseRequestProto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Orbit.Shared.Proto.AbandonAddressableLeaseResponseProto> __Marshaller_Orbit_Shared_AbandonAddressableLeaseResponseProto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Orbit.Shared.Proto.AbandonAddressableLeaseResponseProto.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Orbit.Shared.Proto.RenewAddressableLeaseRequestProto, global::Orbit.Shared.Proto.RenewAddressableLeaseResponseProto> __Method_RenewLease = new grpc::Method<global::Orbit.Shared.Proto.RenewAddressableLeaseRequestProto, global::Orbit.Shared.Proto.RenewAddressableLeaseResponseProto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RenewLease",
        __Marshaller_Orbit_Shared_RenewAddressableLeaseRequestProto,
        __Marshaller_Orbit_Shared_RenewAddressableLeaseResponseProto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Orbit.Shared.Proto.AbandonAddressableLeaseRequestProto, global::Orbit.Shared.Proto.AbandonAddressableLeaseResponseProto> __Method_AbandonLease = new grpc::Method<global::Orbit.Shared.Proto.AbandonAddressableLeaseRequestProto, global::Orbit.Shared.Proto.AbandonAddressableLeaseResponseProto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AbandonLease",
        __Marshaller_Orbit_Shared_AbandonAddressableLeaseRequestProto,
        __Marshaller_Orbit_Shared_AbandonAddressableLeaseResponseProto);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Orbit.Shared.Proto.AddressableManagementReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AddressableManagement</summary>
    [grpc::BindServiceMethod(typeof(AddressableManagement), "BindService")]
    public abstract partial class AddressableManagementBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Orbit.Shared.Proto.RenewAddressableLeaseResponseProto> RenewLease(global::Orbit.Shared.Proto.RenewAddressableLeaseRequestProto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Orbit.Shared.Proto.AbandonAddressableLeaseResponseProto> AbandonLease(global::Orbit.Shared.Proto.AbandonAddressableLeaseRequestProto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AddressableManagement</summary>
    public partial class AddressableManagementClient : grpc::ClientBase<AddressableManagementClient>
    {
      /// <summary>Creates a new client for AddressableManagement</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AddressableManagementClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AddressableManagement that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AddressableManagementClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AddressableManagementClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AddressableManagementClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Orbit.Shared.Proto.RenewAddressableLeaseResponseProto RenewLease(global::Orbit.Shared.Proto.RenewAddressableLeaseRequestProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RenewLease(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Orbit.Shared.Proto.RenewAddressableLeaseResponseProto RenewLease(global::Orbit.Shared.Proto.RenewAddressableLeaseRequestProto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RenewLease, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Orbit.Shared.Proto.RenewAddressableLeaseResponseProto> RenewLeaseAsync(global::Orbit.Shared.Proto.RenewAddressableLeaseRequestProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RenewLeaseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Orbit.Shared.Proto.RenewAddressableLeaseResponseProto> RenewLeaseAsync(global::Orbit.Shared.Proto.RenewAddressableLeaseRequestProto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RenewLease, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Orbit.Shared.Proto.AbandonAddressableLeaseResponseProto AbandonLease(global::Orbit.Shared.Proto.AbandonAddressableLeaseRequestProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AbandonLease(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Orbit.Shared.Proto.AbandonAddressableLeaseResponseProto AbandonLease(global::Orbit.Shared.Proto.AbandonAddressableLeaseRequestProto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AbandonLease, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Orbit.Shared.Proto.AbandonAddressableLeaseResponseProto> AbandonLeaseAsync(global::Orbit.Shared.Proto.AbandonAddressableLeaseRequestProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AbandonLeaseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Orbit.Shared.Proto.AbandonAddressableLeaseResponseProto> AbandonLeaseAsync(global::Orbit.Shared.Proto.AbandonAddressableLeaseRequestProto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AbandonLease, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override AddressableManagementClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AddressableManagementClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(AddressableManagementBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RenewLease, serviceImpl.RenewLease)
          .AddMethod(__Method_AbandonLease, serviceImpl.AbandonLease).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AddressableManagementBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RenewLease, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Orbit.Shared.Proto.RenewAddressableLeaseRequestProto, global::Orbit.Shared.Proto.RenewAddressableLeaseResponseProto>(serviceImpl.RenewLease));
      serviceBinder.AddMethod(__Method_AbandonLease, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Orbit.Shared.Proto.AbandonAddressableLeaseRequestProto, global::Orbit.Shared.Proto.AbandonAddressableLeaseResponseProto>(serviceImpl.AbandonLease));
    }

  }
}
#endregion
