// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: orbit/shared/connection.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Orbit.Shared.Proto {

  /// <summary>Holder for reflection information generated from orbit/shared/connection.proto</summary>
  public static partial class ConnectionReflection {

    #region Descriptor
    /// <summary>File descriptor for orbit/shared/connection.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConnectionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1vcmJpdC9zaGFyZWQvY29ubmVjdGlvbi5wcm90bxIMT3JiaXQuU2hhcmVk",
            "GhtvcmJpdC9zaGFyZWQvbWVzc2FnZXMucHJvdG8yVgoKQ29ubmVjdGlvbhJI",
            "CgpPcGVuU3RyZWFtEhouT3JiaXQuU2hhcmVkLk1lc3NhZ2VQcm90bxoaLk9y",
            "Yml0LlNoYXJlZC5NZXNzYWdlUHJvdG8oATABQhWqAhJPcmJpdC5TaGFyZWQu",
            "UHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Orbit.Shared.Proto.MessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
