// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: orbit/shared/messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Orbit.Shared.Proto {

  /// <summary>Holder for reflection information generated from orbit/shared/messages.proto</summary>
  public static partial class MessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for orbit/shared/messages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtvcmJpdC9zaGFyZWQvbWVzc2FnZXMucHJvdG8SDE9yYml0LlNoYXJlZBoe",
            "b3JiaXQvc2hhcmVkL2FkZHJlc3NhYmxlLnByb3RvGhdvcmJpdC9zaGFyZWQv",
            "bm9kZS5wcm90byLEAQoMTWVzc2FnZVByb3RvEhEKCW1lc3NhZ2VJZBgBIAEo",
            "AxIpCgZzb3VyY2UYAiABKAsyGS5PcmJpdC5TaGFyZWQuTm9kZUlkUHJvdG8S",
            "MAoGdGFyZ2V0GAMgASgLMiAuT3JiaXQuU2hhcmVkLk1lc3NhZ2VUYXJnZXRQ",
            "cm90bxIyCgdjb250ZW50GAQgASgLMiEuT3JiaXQuU2hhcmVkLk1lc3NhZ2VD",
            "b250ZW50UHJvdG8SEAoIYXR0ZW1wdHMYBSABKAMiogIKEk1lc3NhZ2VUYXJn",
            "ZXRQcm90bxJBCg11bmljYXN0VGFyZ2V0GAEgASgLMiguT3JiaXQuU2hhcmVk",
            "Lk1lc3NhZ2VUYXJnZXRQcm90by5VbmljYXN0SAASTQoTcm91dGVkVW5pY2Fz",
            "dFRhcmdldBgCIAEoCzIuLk9yYml0LlNoYXJlZC5NZXNzYWdlVGFyZ2V0UHJv",
            "dG8uUm91dGVkVW5pY2FzdEgAGjQKB1VuaWNhc3QSKQoGdGFyZ2V0GAEgASgL",
            "MhkuT3JiaXQuU2hhcmVkLk5vZGVJZFByb3RvGjoKDVJvdXRlZFVuaWNhc3QS",
            "KQoGdGFyZ2V0GAEgAygLMhkuT3JiaXQuU2hhcmVkLk5vZGVJZFByb3RvQggK",
            "BnRhcmdldCKsAwoTTWVzc2FnZUNvbnRlbnRQcm90bxIpCgVlcnJvchgBIAEo",
            "CzIYLk9yYml0LlNoYXJlZC5FcnJvclByb3RvSAASQAoMaW5mb19yZXF1ZXN0",
            "GAIgASgLMiguT3JiaXQuU2hhcmVkLkNvbm5lY3Rpb25JbmZvUmVxdWVzdFBy",
            "b3RvSAASQgoNaW5mb19yZXNwb25zZRgDIAEoCzIpLk9yYml0LlNoYXJlZC5D",
            "b25uZWN0aW9uSW5mb1Jlc3BvbnNlUHJvdG9IABJCChJpbnZvY2F0aW9uX3Jl",
            "cXVlc3QYBCABKAsyJC5PcmJpdC5TaGFyZWQuSW52b2NhdGlvblJlcXVlc3RQ",
            "cm90b0gAEkQKE2ludm9jYXRpb25fcmVzcG9uc2UYBSABKAsyJS5PcmJpdC5T",
            "aGFyZWQuSW52b2NhdGlvblJlc3BvbnNlUHJvdG9IABJPChlpbnZvY2F0aW9u",
            "X3Jlc3BvbnNlX2Vycm9yGAYgASgLMiouT3JiaXQuU2hhcmVkLkludm9jYXRp",
            "b25SZXNwb25zZUVycm9yUHJvdG9IAEIJCgdjb250ZW50IhwKGkNvbm5lY3Rp",
            "b25JbmZvUmVxdWVzdFByb3RvIkgKG0Nvbm5lY3Rpb25JbmZvUmVzcG9uc2VQ",
            "cm90bxIpCgZub2RlSWQYASABKAsyGS5PcmJpdC5TaGFyZWQuTm9kZUlkUHJv",
            "dG8irAEKFkludm9jYXRpb25SZXF1ZXN0UHJvdG8SOgoJcmVmZXJlbmNlGAEg",
            "ASgLMicuT3JiaXQuU2hhcmVkLkFkZHJlc3NhYmxlUmVmZXJlbmNlUHJvdG8S",
            "DgoGbWV0aG9kGAIgASgJEhEKCWFyZ3VtZW50cxgDIAEoCRIzCgZyZWFzb24Y",
            "BCABKA4yIy5PcmJpdC5TaGFyZWQuSW52b2NhdGlvblJlYXNvblByb3RvIigK",
            "F0ludm9jYXRpb25SZXNwb25zZVByb3RvEg0KBXZhbHVlGAEgASgJIkUKHElu",
            "dm9jYXRpb25SZXNwb25zZUVycm9yUHJvdG8SEwoLZGVzY3JpcHRpb24YASAB",
            "KAkSEAoIcGxhdGZvcm0YAiABKAkiIQoKRXJyb3JQcm90bxITCgtkZXNjcmlw",
            "dGlvbhgBIAEoCSo1ChVJbnZvY2F0aW9uUmVhc29uUHJvdG8SDgoKaW52b2Nh",
            "dGlvbhAAEgwKCHJlcm91dGVkEAFCFaoCEk9yYml0LlNoYXJlZC5Qcm90b2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Orbit.Shared.Proto.AddressableReflection.Descriptor, global::Orbit.Shared.Proto.NodeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Orbit.Shared.Proto.InvocationReasonProto), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.MessageProto), global::Orbit.Shared.Proto.MessageProto.Parser, new[]{ "MessageId", "Source", "Target", "Content", "Attempts" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.MessageTargetProto), global::Orbit.Shared.Proto.MessageTargetProto.Parser, new[]{ "UnicastTarget", "RoutedUnicastTarget" }, new[]{ "Target" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.MessageTargetProto.Types.Unicast), global::Orbit.Shared.Proto.MessageTargetProto.Types.Unicast.Parser, new[]{ "Target" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.MessageTargetProto.Types.RoutedUnicast), global::Orbit.Shared.Proto.MessageTargetProto.Types.RoutedUnicast.Parser, new[]{ "Target" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.MessageContentProto), global::Orbit.Shared.Proto.MessageContentProto.Parser, new[]{ "Error", "InfoRequest", "InfoResponse", "InvocationRequest", "InvocationResponse", "InvocationResponseError" }, new[]{ "Content" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.ConnectionInfoRequestProto), global::Orbit.Shared.Proto.ConnectionInfoRequestProto.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.ConnectionInfoResponseProto), global::Orbit.Shared.Proto.ConnectionInfoResponseProto.Parser, new[]{ "NodeId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.InvocationRequestProto), global::Orbit.Shared.Proto.InvocationRequestProto.Parser, new[]{ "Reference", "Method", "Arguments", "Reason" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.InvocationResponseProto), global::Orbit.Shared.Proto.InvocationResponseProto.Parser, new[]{ "Value" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.InvocationResponseErrorProto), global::Orbit.Shared.Proto.InvocationResponseErrorProto.Parser, new[]{ "Description", "Platform" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Orbit.Shared.Proto.ErrorProto), global::Orbit.Shared.Proto.ErrorProto.Parser, new[]{ "Description" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum InvocationReasonProto {
    [pbr::OriginalName("invocation")] Invocation = 0,
    [pbr::OriginalName("rerouted")] Rerouted = 1,
  }

  #endregion

  #region Messages
  public sealed partial class MessageProto : pb::IMessage<MessageProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageProto> _parser = new pb::MessageParser<MessageProto>(() => new MessageProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MessageProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.MessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageProto(MessageProto other) : this() {
      messageId_ = other.messageId_;
      source_ = other.source_ != null ? other.source_.Clone() : null;
      target_ = other.target_ != null ? other.target_.Clone() : null;
      content_ = other.content_ != null ? other.content_.Clone() : null;
      attempts_ = other.attempts_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageProto Clone() {
      return new MessageProto(this);
    }

    /// <summary>Field number for the "messageId" field.</summary>
    public const int MessageIdFieldNumber = 1;
    private long messageId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long MessageId {
      get { return messageId_; }
      set {
        messageId_ = value;
      }
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 2;
    private global::Orbit.Shared.Proto.NodeIdProto source_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.NodeIdProto Source {
      get { return source_; }
      set {
        source_ = value;
      }
    }

    /// <summary>Field number for the "target" field.</summary>
    public const int TargetFieldNumber = 3;
    private global::Orbit.Shared.Proto.MessageTargetProto target_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.MessageTargetProto Target {
      get { return target_; }
      set {
        target_ = value;
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 4;
    private global::Orbit.Shared.Proto.MessageContentProto content_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.MessageContentProto Content {
      get { return content_; }
      set {
        content_ = value;
      }
    }

    /// <summary>Field number for the "attempts" field.</summary>
    public const int AttemptsFieldNumber = 5;
    private long attempts_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Attempts {
      get { return attempts_; }
      set {
        attempts_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MessageProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MessageProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageId != other.MessageId) return false;
      if (!object.Equals(Source, other.Source)) return false;
      if (!object.Equals(Target, other.Target)) return false;
      if (!object.Equals(Content, other.Content)) return false;
      if (Attempts != other.Attempts) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageId != 0L) hash ^= MessageId.GetHashCode();
      if (source_ != null) hash ^= Source.GetHashCode();
      if (target_ != null) hash ^= Target.GetHashCode();
      if (content_ != null) hash ^= Content.GetHashCode();
      if (Attempts != 0L) hash ^= Attempts.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(MessageId);
      }
      if (source_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Source);
      }
      if (target_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Target);
      }
      if (content_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Content);
      }
      if (Attempts != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Attempts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(MessageId);
      }
      if (source_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Source);
      }
      if (target_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Target);
      }
      if (content_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Content);
      }
      if (Attempts != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Attempts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MessageId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MessageId);
      }
      if (source_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Source);
      }
      if (target_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Target);
      }
      if (content_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Content);
      }
      if (Attempts != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Attempts);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MessageProto other) {
      if (other == null) {
        return;
      }
      if (other.MessageId != 0L) {
        MessageId = other.MessageId;
      }
      if (other.source_ != null) {
        if (source_ == null) {
          Source = new global::Orbit.Shared.Proto.NodeIdProto();
        }
        Source.MergeFrom(other.Source);
      }
      if (other.target_ != null) {
        if (target_ == null) {
          Target = new global::Orbit.Shared.Proto.MessageTargetProto();
        }
        Target.MergeFrom(other.Target);
      }
      if (other.content_ != null) {
        if (content_ == null) {
          Content = new global::Orbit.Shared.Proto.MessageContentProto();
        }
        Content.MergeFrom(other.Content);
      }
      if (other.Attempts != 0L) {
        Attempts = other.Attempts;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageId = input.ReadInt64();
            break;
          }
          case 18: {
            if (source_ == null) {
              Source = new global::Orbit.Shared.Proto.NodeIdProto();
            }
            input.ReadMessage(Source);
            break;
          }
          case 26: {
            if (target_ == null) {
              Target = new global::Orbit.Shared.Proto.MessageTargetProto();
            }
            input.ReadMessage(Target);
            break;
          }
          case 34: {
            if (content_ == null) {
              Content = new global::Orbit.Shared.Proto.MessageContentProto();
            }
            input.ReadMessage(Content);
            break;
          }
          case 40: {
            Attempts = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MessageId = input.ReadInt64();
            break;
          }
          case 18: {
            if (source_ == null) {
              Source = new global::Orbit.Shared.Proto.NodeIdProto();
            }
            input.ReadMessage(Source);
            break;
          }
          case 26: {
            if (target_ == null) {
              Target = new global::Orbit.Shared.Proto.MessageTargetProto();
            }
            input.ReadMessage(Target);
            break;
          }
          case 34: {
            if (content_ == null) {
              Content = new global::Orbit.Shared.Proto.MessageContentProto();
            }
            input.ReadMessage(Content);
            break;
          }
          case 40: {
            Attempts = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MessageTargetProto : pb::IMessage<MessageTargetProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageTargetProto> _parser = new pb::MessageParser<MessageTargetProto>(() => new MessageTargetProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MessageTargetProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.MessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageTargetProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageTargetProto(MessageTargetProto other) : this() {
      switch (other.TargetCase) {
        case TargetOneofCase.UnicastTarget:
          UnicastTarget = other.UnicastTarget.Clone();
          break;
        case TargetOneofCase.RoutedUnicastTarget:
          RoutedUnicastTarget = other.RoutedUnicastTarget.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageTargetProto Clone() {
      return new MessageTargetProto(this);
    }

    /// <summary>Field number for the "unicastTarget" field.</summary>
    public const int UnicastTargetFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.MessageTargetProto.Types.Unicast UnicastTarget {
      get { return targetCase_ == TargetOneofCase.UnicastTarget ? (global::Orbit.Shared.Proto.MessageTargetProto.Types.Unicast) target_ : null; }
      set {
        target_ = value;
        targetCase_ = value == null ? TargetOneofCase.None : TargetOneofCase.UnicastTarget;
      }
    }

    /// <summary>Field number for the "routedUnicastTarget" field.</summary>
    public const int RoutedUnicastTargetFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.MessageTargetProto.Types.RoutedUnicast RoutedUnicastTarget {
      get { return targetCase_ == TargetOneofCase.RoutedUnicastTarget ? (global::Orbit.Shared.Proto.MessageTargetProto.Types.RoutedUnicast) target_ : null; }
      set {
        target_ = value;
        targetCase_ = value == null ? TargetOneofCase.None : TargetOneofCase.RoutedUnicastTarget;
      }
    }

    private object target_;
    /// <summary>Enum of possible cases for the "target" oneof.</summary>
    public enum TargetOneofCase {
      None = 0,
      UnicastTarget = 1,
      RoutedUnicastTarget = 2,
    }
    private TargetOneofCase targetCase_ = TargetOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TargetOneofCase TargetCase {
      get { return targetCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTarget() {
      targetCase_ = TargetOneofCase.None;
      target_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MessageTargetProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MessageTargetProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UnicastTarget, other.UnicastTarget)) return false;
      if (!object.Equals(RoutedUnicastTarget, other.RoutedUnicastTarget)) return false;
      if (TargetCase != other.TargetCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (targetCase_ == TargetOneofCase.UnicastTarget) hash ^= UnicastTarget.GetHashCode();
      if (targetCase_ == TargetOneofCase.RoutedUnicastTarget) hash ^= RoutedUnicastTarget.GetHashCode();
      hash ^= (int) targetCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (targetCase_ == TargetOneofCase.UnicastTarget) {
        output.WriteRawTag(10);
        output.WriteMessage(UnicastTarget);
      }
      if (targetCase_ == TargetOneofCase.RoutedUnicastTarget) {
        output.WriteRawTag(18);
        output.WriteMessage(RoutedUnicastTarget);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (targetCase_ == TargetOneofCase.UnicastTarget) {
        output.WriteRawTag(10);
        output.WriteMessage(UnicastTarget);
      }
      if (targetCase_ == TargetOneofCase.RoutedUnicastTarget) {
        output.WriteRawTag(18);
        output.WriteMessage(RoutedUnicastTarget);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (targetCase_ == TargetOneofCase.UnicastTarget) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnicastTarget);
      }
      if (targetCase_ == TargetOneofCase.RoutedUnicastTarget) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoutedUnicastTarget);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MessageTargetProto other) {
      if (other == null) {
        return;
      }
      switch (other.TargetCase) {
        case TargetOneofCase.UnicastTarget:
          if (UnicastTarget == null) {
            UnicastTarget = new global::Orbit.Shared.Proto.MessageTargetProto.Types.Unicast();
          }
          UnicastTarget.MergeFrom(other.UnicastTarget);
          break;
        case TargetOneofCase.RoutedUnicastTarget:
          if (RoutedUnicastTarget == null) {
            RoutedUnicastTarget = new global::Orbit.Shared.Proto.MessageTargetProto.Types.RoutedUnicast();
          }
          RoutedUnicastTarget.MergeFrom(other.RoutedUnicastTarget);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Orbit.Shared.Proto.MessageTargetProto.Types.Unicast subBuilder = new global::Orbit.Shared.Proto.MessageTargetProto.Types.Unicast();
            if (targetCase_ == TargetOneofCase.UnicastTarget) {
              subBuilder.MergeFrom(UnicastTarget);
            }
            input.ReadMessage(subBuilder);
            UnicastTarget = subBuilder;
            break;
          }
          case 18: {
            global::Orbit.Shared.Proto.MessageTargetProto.Types.RoutedUnicast subBuilder = new global::Orbit.Shared.Proto.MessageTargetProto.Types.RoutedUnicast();
            if (targetCase_ == TargetOneofCase.RoutedUnicastTarget) {
              subBuilder.MergeFrom(RoutedUnicastTarget);
            }
            input.ReadMessage(subBuilder);
            RoutedUnicastTarget = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Orbit.Shared.Proto.MessageTargetProto.Types.Unicast subBuilder = new global::Orbit.Shared.Proto.MessageTargetProto.Types.Unicast();
            if (targetCase_ == TargetOneofCase.UnicastTarget) {
              subBuilder.MergeFrom(UnicastTarget);
            }
            input.ReadMessage(subBuilder);
            UnicastTarget = subBuilder;
            break;
          }
          case 18: {
            global::Orbit.Shared.Proto.MessageTargetProto.Types.RoutedUnicast subBuilder = new global::Orbit.Shared.Proto.MessageTargetProto.Types.RoutedUnicast();
            if (targetCase_ == TargetOneofCase.RoutedUnicastTarget) {
              subBuilder.MergeFrom(RoutedUnicastTarget);
            }
            input.ReadMessage(subBuilder);
            RoutedUnicastTarget = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MessageTargetProto message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Unicast : pb::IMessage<Unicast>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Unicast> _parser = new pb::MessageParser<Unicast>(() => new Unicast());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Unicast> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Orbit.Shared.Proto.MessageTargetProto.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Unicast() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Unicast(Unicast other) : this() {
          target_ = other.target_ != null ? other.target_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Unicast Clone() {
          return new Unicast(this);
        }

        /// <summary>Field number for the "target" field.</summary>
        public const int TargetFieldNumber = 1;
        private global::Orbit.Shared.Proto.NodeIdProto target_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Orbit.Shared.Proto.NodeIdProto Target {
          get { return target_; }
          set {
            target_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Unicast);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Unicast other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Target, other.Target)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (target_ != null) hash ^= Target.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (target_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Target);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (target_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Target);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (target_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Target);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Unicast other) {
          if (other == null) {
            return;
          }
          if (other.target_ != null) {
            if (target_ == null) {
              Target = new global::Orbit.Shared.Proto.NodeIdProto();
            }
            Target.MergeFrom(other.Target);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (target_ == null) {
                  Target = new global::Orbit.Shared.Proto.NodeIdProto();
                }
                input.ReadMessage(Target);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (target_ == null) {
                  Target = new global::Orbit.Shared.Proto.NodeIdProto();
                }
                input.ReadMessage(Target);
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class RoutedUnicast : pb::IMessage<RoutedUnicast>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<RoutedUnicast> _parser = new pb::MessageParser<RoutedUnicast>(() => new RoutedUnicast());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<RoutedUnicast> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Orbit.Shared.Proto.MessageTargetProto.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public RoutedUnicast() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public RoutedUnicast(RoutedUnicast other) : this() {
          target_ = other.target_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public RoutedUnicast Clone() {
          return new RoutedUnicast(this);
        }

        /// <summary>Field number for the "target" field.</summary>
        public const int TargetFieldNumber = 1;
        private static readonly pb::FieldCodec<global::Orbit.Shared.Proto.NodeIdProto> _repeated_target_codec
            = pb::FieldCodec.ForMessage(10, global::Orbit.Shared.Proto.NodeIdProto.Parser);
        private readonly pbc::RepeatedField<global::Orbit.Shared.Proto.NodeIdProto> target_ = new pbc::RepeatedField<global::Orbit.Shared.Proto.NodeIdProto>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::Orbit.Shared.Proto.NodeIdProto> Target {
          get { return target_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as RoutedUnicast);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(RoutedUnicast other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!target_.Equals(other.target_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= target_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          target_.WriteTo(output, _repeated_target_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          target_.WriteTo(ref output, _repeated_target_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          size += target_.CalculateSize(_repeated_target_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(RoutedUnicast other) {
          if (other == null) {
            return;
          }
          target_.Add(other.target_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                target_.AddEntriesFrom(input, _repeated_target_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                target_.AddEntriesFrom(ref input, _repeated_target_codec);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  public sealed partial class MessageContentProto : pb::IMessage<MessageContentProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageContentProto> _parser = new pb::MessageParser<MessageContentProto>(() => new MessageContentProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MessageContentProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.MessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageContentProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageContentProto(MessageContentProto other) : this() {
      switch (other.ContentCase) {
        case ContentOneofCase.Error:
          Error = other.Error.Clone();
          break;
        case ContentOneofCase.InfoRequest:
          InfoRequest = other.InfoRequest.Clone();
          break;
        case ContentOneofCase.InfoResponse:
          InfoResponse = other.InfoResponse.Clone();
          break;
        case ContentOneofCase.InvocationRequest:
          InvocationRequest = other.InvocationRequest.Clone();
          break;
        case ContentOneofCase.InvocationResponse:
          InvocationResponse = other.InvocationResponse.Clone();
          break;
        case ContentOneofCase.InvocationResponseError:
          InvocationResponseError = other.InvocationResponseError.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageContentProto Clone() {
      return new MessageContentProto(this);
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.ErrorProto Error {
      get { return contentCase_ == ContentOneofCase.Error ? (global::Orbit.Shared.Proto.ErrorProto) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.Error;
      }
    }

    /// <summary>Field number for the "info_request" field.</summary>
    public const int InfoRequestFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.ConnectionInfoRequestProto InfoRequest {
      get { return contentCase_ == ContentOneofCase.InfoRequest ? (global::Orbit.Shared.Proto.ConnectionInfoRequestProto) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.InfoRequest;
      }
    }

    /// <summary>Field number for the "info_response" field.</summary>
    public const int InfoResponseFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.ConnectionInfoResponseProto InfoResponse {
      get { return contentCase_ == ContentOneofCase.InfoResponse ? (global::Orbit.Shared.Proto.ConnectionInfoResponseProto) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.InfoResponse;
      }
    }

    /// <summary>Field number for the "invocation_request" field.</summary>
    public const int InvocationRequestFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.InvocationRequestProto InvocationRequest {
      get { return contentCase_ == ContentOneofCase.InvocationRequest ? (global::Orbit.Shared.Proto.InvocationRequestProto) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.InvocationRequest;
      }
    }

    /// <summary>Field number for the "invocation_response" field.</summary>
    public const int InvocationResponseFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.InvocationResponseProto InvocationResponse {
      get { return contentCase_ == ContentOneofCase.InvocationResponse ? (global::Orbit.Shared.Proto.InvocationResponseProto) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.InvocationResponse;
      }
    }

    /// <summary>Field number for the "invocation_response_error" field.</summary>
    public const int InvocationResponseErrorFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.InvocationResponseErrorProto InvocationResponseError {
      get { return contentCase_ == ContentOneofCase.InvocationResponseError ? (global::Orbit.Shared.Proto.InvocationResponseErrorProto) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.InvocationResponseError;
      }
    }

    private object content_;
    /// <summary>Enum of possible cases for the "content" oneof.</summary>
    public enum ContentOneofCase {
      None = 0,
      Error = 1,
      InfoRequest = 2,
      InfoResponse = 3,
      InvocationRequest = 4,
      InvocationResponse = 5,
      InvocationResponseError = 6,
    }
    private ContentOneofCase contentCase_ = ContentOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContentOneofCase ContentCase {
      get { return contentCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearContent() {
      contentCase_ = ContentOneofCase.None;
      content_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MessageContentProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MessageContentProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Error, other.Error)) return false;
      if (!object.Equals(InfoRequest, other.InfoRequest)) return false;
      if (!object.Equals(InfoResponse, other.InfoResponse)) return false;
      if (!object.Equals(InvocationRequest, other.InvocationRequest)) return false;
      if (!object.Equals(InvocationResponse, other.InvocationResponse)) return false;
      if (!object.Equals(InvocationResponseError, other.InvocationResponseError)) return false;
      if (ContentCase != other.ContentCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (contentCase_ == ContentOneofCase.Error) hash ^= Error.GetHashCode();
      if (contentCase_ == ContentOneofCase.InfoRequest) hash ^= InfoRequest.GetHashCode();
      if (contentCase_ == ContentOneofCase.InfoResponse) hash ^= InfoResponse.GetHashCode();
      if (contentCase_ == ContentOneofCase.InvocationRequest) hash ^= InvocationRequest.GetHashCode();
      if (contentCase_ == ContentOneofCase.InvocationResponse) hash ^= InvocationResponse.GetHashCode();
      if (contentCase_ == ContentOneofCase.InvocationResponseError) hash ^= InvocationResponseError.GetHashCode();
      hash ^= (int) contentCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (contentCase_ == ContentOneofCase.Error) {
        output.WriteRawTag(10);
        output.WriteMessage(Error);
      }
      if (contentCase_ == ContentOneofCase.InfoRequest) {
        output.WriteRawTag(18);
        output.WriteMessage(InfoRequest);
      }
      if (contentCase_ == ContentOneofCase.InfoResponse) {
        output.WriteRawTag(26);
        output.WriteMessage(InfoResponse);
      }
      if (contentCase_ == ContentOneofCase.InvocationRequest) {
        output.WriteRawTag(34);
        output.WriteMessage(InvocationRequest);
      }
      if (contentCase_ == ContentOneofCase.InvocationResponse) {
        output.WriteRawTag(42);
        output.WriteMessage(InvocationResponse);
      }
      if (contentCase_ == ContentOneofCase.InvocationResponseError) {
        output.WriteRawTag(50);
        output.WriteMessage(InvocationResponseError);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (contentCase_ == ContentOneofCase.Error) {
        output.WriteRawTag(10);
        output.WriteMessage(Error);
      }
      if (contentCase_ == ContentOneofCase.InfoRequest) {
        output.WriteRawTag(18);
        output.WriteMessage(InfoRequest);
      }
      if (contentCase_ == ContentOneofCase.InfoResponse) {
        output.WriteRawTag(26);
        output.WriteMessage(InfoResponse);
      }
      if (contentCase_ == ContentOneofCase.InvocationRequest) {
        output.WriteRawTag(34);
        output.WriteMessage(InvocationRequest);
      }
      if (contentCase_ == ContentOneofCase.InvocationResponse) {
        output.WriteRawTag(42);
        output.WriteMessage(InvocationResponse);
      }
      if (contentCase_ == ContentOneofCase.InvocationResponseError) {
        output.WriteRawTag(50);
        output.WriteMessage(InvocationResponseError);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (contentCase_ == ContentOneofCase.Error) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
      }
      if (contentCase_ == ContentOneofCase.InfoRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InfoRequest);
      }
      if (contentCase_ == ContentOneofCase.InfoResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InfoResponse);
      }
      if (contentCase_ == ContentOneofCase.InvocationRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InvocationRequest);
      }
      if (contentCase_ == ContentOneofCase.InvocationResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InvocationResponse);
      }
      if (contentCase_ == ContentOneofCase.InvocationResponseError) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InvocationResponseError);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MessageContentProto other) {
      if (other == null) {
        return;
      }
      switch (other.ContentCase) {
        case ContentOneofCase.Error:
          if (Error == null) {
            Error = new global::Orbit.Shared.Proto.ErrorProto();
          }
          Error.MergeFrom(other.Error);
          break;
        case ContentOneofCase.InfoRequest:
          if (InfoRequest == null) {
            InfoRequest = new global::Orbit.Shared.Proto.ConnectionInfoRequestProto();
          }
          InfoRequest.MergeFrom(other.InfoRequest);
          break;
        case ContentOneofCase.InfoResponse:
          if (InfoResponse == null) {
            InfoResponse = new global::Orbit.Shared.Proto.ConnectionInfoResponseProto();
          }
          InfoResponse.MergeFrom(other.InfoResponse);
          break;
        case ContentOneofCase.InvocationRequest:
          if (InvocationRequest == null) {
            InvocationRequest = new global::Orbit.Shared.Proto.InvocationRequestProto();
          }
          InvocationRequest.MergeFrom(other.InvocationRequest);
          break;
        case ContentOneofCase.InvocationResponse:
          if (InvocationResponse == null) {
            InvocationResponse = new global::Orbit.Shared.Proto.InvocationResponseProto();
          }
          InvocationResponse.MergeFrom(other.InvocationResponse);
          break;
        case ContentOneofCase.InvocationResponseError:
          if (InvocationResponseError == null) {
            InvocationResponseError = new global::Orbit.Shared.Proto.InvocationResponseErrorProto();
          }
          InvocationResponseError.MergeFrom(other.InvocationResponseError);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Orbit.Shared.Proto.ErrorProto subBuilder = new global::Orbit.Shared.Proto.ErrorProto();
            if (contentCase_ == ContentOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
          case 18: {
            global::Orbit.Shared.Proto.ConnectionInfoRequestProto subBuilder = new global::Orbit.Shared.Proto.ConnectionInfoRequestProto();
            if (contentCase_ == ContentOneofCase.InfoRequest) {
              subBuilder.MergeFrom(InfoRequest);
            }
            input.ReadMessage(subBuilder);
            InfoRequest = subBuilder;
            break;
          }
          case 26: {
            global::Orbit.Shared.Proto.ConnectionInfoResponseProto subBuilder = new global::Orbit.Shared.Proto.ConnectionInfoResponseProto();
            if (contentCase_ == ContentOneofCase.InfoResponse) {
              subBuilder.MergeFrom(InfoResponse);
            }
            input.ReadMessage(subBuilder);
            InfoResponse = subBuilder;
            break;
          }
          case 34: {
            global::Orbit.Shared.Proto.InvocationRequestProto subBuilder = new global::Orbit.Shared.Proto.InvocationRequestProto();
            if (contentCase_ == ContentOneofCase.InvocationRequest) {
              subBuilder.MergeFrom(InvocationRequest);
            }
            input.ReadMessage(subBuilder);
            InvocationRequest = subBuilder;
            break;
          }
          case 42: {
            global::Orbit.Shared.Proto.InvocationResponseProto subBuilder = new global::Orbit.Shared.Proto.InvocationResponseProto();
            if (contentCase_ == ContentOneofCase.InvocationResponse) {
              subBuilder.MergeFrom(InvocationResponse);
            }
            input.ReadMessage(subBuilder);
            InvocationResponse = subBuilder;
            break;
          }
          case 50: {
            global::Orbit.Shared.Proto.InvocationResponseErrorProto subBuilder = new global::Orbit.Shared.Proto.InvocationResponseErrorProto();
            if (contentCase_ == ContentOneofCase.InvocationResponseError) {
              subBuilder.MergeFrom(InvocationResponseError);
            }
            input.ReadMessage(subBuilder);
            InvocationResponseError = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Orbit.Shared.Proto.ErrorProto subBuilder = new global::Orbit.Shared.Proto.ErrorProto();
            if (contentCase_ == ContentOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
          case 18: {
            global::Orbit.Shared.Proto.ConnectionInfoRequestProto subBuilder = new global::Orbit.Shared.Proto.ConnectionInfoRequestProto();
            if (contentCase_ == ContentOneofCase.InfoRequest) {
              subBuilder.MergeFrom(InfoRequest);
            }
            input.ReadMessage(subBuilder);
            InfoRequest = subBuilder;
            break;
          }
          case 26: {
            global::Orbit.Shared.Proto.ConnectionInfoResponseProto subBuilder = new global::Orbit.Shared.Proto.ConnectionInfoResponseProto();
            if (contentCase_ == ContentOneofCase.InfoResponse) {
              subBuilder.MergeFrom(InfoResponse);
            }
            input.ReadMessage(subBuilder);
            InfoResponse = subBuilder;
            break;
          }
          case 34: {
            global::Orbit.Shared.Proto.InvocationRequestProto subBuilder = new global::Orbit.Shared.Proto.InvocationRequestProto();
            if (contentCase_ == ContentOneofCase.InvocationRequest) {
              subBuilder.MergeFrom(InvocationRequest);
            }
            input.ReadMessage(subBuilder);
            InvocationRequest = subBuilder;
            break;
          }
          case 42: {
            global::Orbit.Shared.Proto.InvocationResponseProto subBuilder = new global::Orbit.Shared.Proto.InvocationResponseProto();
            if (contentCase_ == ContentOneofCase.InvocationResponse) {
              subBuilder.MergeFrom(InvocationResponse);
            }
            input.ReadMessage(subBuilder);
            InvocationResponse = subBuilder;
            break;
          }
          case 50: {
            global::Orbit.Shared.Proto.InvocationResponseErrorProto subBuilder = new global::Orbit.Shared.Proto.InvocationResponseErrorProto();
            if (contentCase_ == ContentOneofCase.InvocationResponseError) {
              subBuilder.MergeFrom(InvocationResponseError);
            }
            input.ReadMessage(subBuilder);
            InvocationResponseError = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ConnectionInfoRequestProto : pb::IMessage<ConnectionInfoRequestProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConnectionInfoRequestProto> _parser = new pb::MessageParser<ConnectionInfoRequestProto>(() => new ConnectionInfoRequestProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConnectionInfoRequestProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.MessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectionInfoRequestProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectionInfoRequestProto(ConnectionInfoRequestProto other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectionInfoRequestProto Clone() {
      return new ConnectionInfoRequestProto(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConnectionInfoRequestProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConnectionInfoRequestProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConnectionInfoRequestProto other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class ConnectionInfoResponseProto : pb::IMessage<ConnectionInfoResponseProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConnectionInfoResponseProto> _parser = new pb::MessageParser<ConnectionInfoResponseProto>(() => new ConnectionInfoResponseProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConnectionInfoResponseProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.MessagesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectionInfoResponseProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectionInfoResponseProto(ConnectionInfoResponseProto other) : this() {
      nodeId_ = other.nodeId_ != null ? other.nodeId_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectionInfoResponseProto Clone() {
      return new ConnectionInfoResponseProto(this);
    }

    /// <summary>Field number for the "nodeId" field.</summary>
    public const int NodeIdFieldNumber = 1;
    private global::Orbit.Shared.Proto.NodeIdProto nodeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.NodeIdProto NodeId {
      get { return nodeId_; }
      set {
        nodeId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConnectionInfoResponseProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConnectionInfoResponseProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(NodeId, other.NodeId)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (nodeId_ != null) hash ^= NodeId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (nodeId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(NodeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (nodeId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(NodeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (nodeId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NodeId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConnectionInfoResponseProto other) {
      if (other == null) {
        return;
      }
      if (other.nodeId_ != null) {
        if (nodeId_ == null) {
          NodeId = new global::Orbit.Shared.Proto.NodeIdProto();
        }
        NodeId.MergeFrom(other.NodeId);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (nodeId_ == null) {
              NodeId = new global::Orbit.Shared.Proto.NodeIdProto();
            }
            input.ReadMessage(NodeId);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (nodeId_ == null) {
              NodeId = new global::Orbit.Shared.Proto.NodeIdProto();
            }
            input.ReadMessage(NodeId);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class InvocationRequestProto : pb::IMessage<InvocationRequestProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InvocationRequestProto> _parser = new pb::MessageParser<InvocationRequestProto>(() => new InvocationRequestProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InvocationRequestProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.MessagesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvocationRequestProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvocationRequestProto(InvocationRequestProto other) : this() {
      reference_ = other.reference_ != null ? other.reference_.Clone() : null;
      method_ = other.method_;
      arguments_ = other.arguments_;
      reason_ = other.reason_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvocationRequestProto Clone() {
      return new InvocationRequestProto(this);
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 1;
    private global::Orbit.Shared.Proto.AddressableReferenceProto reference_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.AddressableReferenceProto Reference {
      get { return reference_; }
      set {
        reference_ = value;
      }
    }

    /// <summary>Field number for the "method" field.</summary>
    public const int MethodFieldNumber = 2;
    private string method_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Method {
      get { return method_; }
      set {
        method_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "arguments" field.</summary>
    public const int ArgumentsFieldNumber = 3;
    private string arguments_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Arguments {
      get { return arguments_; }
      set {
        arguments_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 4;
    private global::Orbit.Shared.Proto.InvocationReasonProto reason_ = global::Orbit.Shared.Proto.InvocationReasonProto.Invocation;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Orbit.Shared.Proto.InvocationReasonProto Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InvocationRequestProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InvocationRequestProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Reference, other.Reference)) return false;
      if (Method != other.Method) return false;
      if (Arguments != other.Arguments) return false;
      if (Reason != other.Reason) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (reference_ != null) hash ^= Reference.GetHashCode();
      if (Method.Length != 0) hash ^= Method.GetHashCode();
      if (Arguments.Length != 0) hash ^= Arguments.GetHashCode();
      if (Reason != global::Orbit.Shared.Proto.InvocationReasonProto.Invocation) hash ^= Reason.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (reference_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Reference);
      }
      if (Method.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Method);
      }
      if (Arguments.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Arguments);
      }
      if (Reason != global::Orbit.Shared.Proto.InvocationReasonProto.Invocation) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Reason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (reference_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Reference);
      }
      if (Method.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Method);
      }
      if (Arguments.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Arguments);
      }
      if (Reason != global::Orbit.Shared.Proto.InvocationReasonProto.Invocation) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Reason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (reference_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reference);
      }
      if (Method.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Method);
      }
      if (Arguments.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Arguments);
      }
      if (Reason != global::Orbit.Shared.Proto.InvocationReasonProto.Invocation) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Reason);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InvocationRequestProto other) {
      if (other == null) {
        return;
      }
      if (other.reference_ != null) {
        if (reference_ == null) {
          Reference = new global::Orbit.Shared.Proto.AddressableReferenceProto();
        }
        Reference.MergeFrom(other.Reference);
      }
      if (other.Method.Length != 0) {
        Method = other.Method;
      }
      if (other.Arguments.Length != 0) {
        Arguments = other.Arguments;
      }
      if (other.Reason != global::Orbit.Shared.Proto.InvocationReasonProto.Invocation) {
        Reason = other.Reason;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (reference_ == null) {
              Reference = new global::Orbit.Shared.Proto.AddressableReferenceProto();
            }
            input.ReadMessage(Reference);
            break;
          }
          case 18: {
            Method = input.ReadString();
            break;
          }
          case 26: {
            Arguments = input.ReadString();
            break;
          }
          case 32: {
            Reason = (global::Orbit.Shared.Proto.InvocationReasonProto) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (reference_ == null) {
              Reference = new global::Orbit.Shared.Proto.AddressableReferenceProto();
            }
            input.ReadMessage(Reference);
            break;
          }
          case 18: {
            Method = input.ReadString();
            break;
          }
          case 26: {
            Arguments = input.ReadString();
            break;
          }
          case 32: {
            Reason = (global::Orbit.Shared.Proto.InvocationReasonProto) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class InvocationResponseProto : pb::IMessage<InvocationResponseProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InvocationResponseProto> _parser = new pb::MessageParser<InvocationResponseProto>(() => new InvocationResponseProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InvocationResponseProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.MessagesReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvocationResponseProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvocationResponseProto(InvocationResponseProto other) : this() {
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvocationResponseProto Clone() {
      return new InvocationResponseProto(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private string value_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InvocationResponseProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InvocationResponseProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Value.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Value.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InvocationResponseProto other) {
      if (other == null) {
        return;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Value = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Value = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class InvocationResponseErrorProto : pb::IMessage<InvocationResponseErrorProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InvocationResponseErrorProto> _parser = new pb::MessageParser<InvocationResponseErrorProto>(() => new InvocationResponseErrorProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InvocationResponseErrorProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.MessagesReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvocationResponseErrorProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvocationResponseErrorProto(InvocationResponseErrorProto other) : this() {
      description_ = other.description_;
      platform_ = other.platform_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvocationResponseErrorProto Clone() {
      return new InvocationResponseErrorProto(this);
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 1;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "platform" field.</summary>
    public const int PlatformFieldNumber = 2;
    private string platform_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Platform {
      get { return platform_; }
      set {
        platform_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InvocationResponseErrorProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InvocationResponseErrorProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Description != other.Description) return false;
      if (Platform != other.Platform) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (Platform.Length != 0) hash ^= Platform.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Description.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Description);
      }
      if (Platform.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Platform);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Description.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Description);
      }
      if (Platform.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Platform);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (Platform.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Platform);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InvocationResponseErrorProto other) {
      if (other == null) {
        return;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.Platform.Length != 0) {
        Platform = other.Platform;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Description = input.ReadString();
            break;
          }
          case 18: {
            Platform = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Description = input.ReadString();
            break;
          }
          case 18: {
            Platform = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ErrorProto : pb::IMessage<ErrorProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ErrorProto> _parser = new pb::MessageParser<ErrorProto>(() => new ErrorProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ErrorProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Orbit.Shared.Proto.MessagesReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ErrorProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ErrorProto(ErrorProto other) : this() {
      description_ = other.description_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ErrorProto Clone() {
      return new ErrorProto(this);
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 1;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ErrorProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ErrorProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Description != other.Description) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Description.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Description.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ErrorProto other) {
      if (other == null) {
        return;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Description = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Description = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
